import { Multiplier } from '../models';

export const INITIAL_MULTIPLIERS: Multiplier[] = [
  {
    id: 'click2x',
    name: 'Sharpened Tools',
    description: 'x2 resources per click.',
    baseCost: 300,
    effect: 2,
    type: 'click',
    purchased: false,
    icon: '⚡',
    unlockCost: 0,
  },
  {
    id: 'auto2x',
    name: 'Overclocked Drones',
    description: 'x2 automated production.',
    baseCost: 1500,
    effect: 2,
    type: 'auto',
    purchased: false,
    icon: '⚙️',
    unlockCost: 500,
  },
  {
    id: 'global50',
    name: 'Alien Tech Discovery',
    description: '+50% all resource generation.',
    baseCost: 8000,
    effect: 1.5,
    type: 'global',
    purchased: false,
    icon: '🧬',
    unlockCost: 5000,
  },
  {
    id: 'click4x',
    name: 'Resonance Amplifier',
    description: 'x2 resources per click (stacks).',
    baseCost: 25000,
    effect: 2,
    type: 'click',
    purchased: false,
    icon: '💎',
    unlockCost: 15000,
  },
  {
    id: 'auto4x',
    name: 'Swarm Intelligence',
    description: 'x2 automated production (stacks).',
    baseCost: 50000,
    effect: 2,
    type: 'auto',
    purchased: false,
    icon: '🧠',
    unlockCost: 30000,
  },
  {
    id: 'global2x',
    name: 'Void Energy Tap',
    description: 'x2 all resource generation.',
    baseCost: 200000,
    effect: 2,
    type: 'global',
    purchased: false,
    icon: '🌀',
    unlockCost: 100000,
  },
];
