import { Planet } from '../models';
import { GAME_MESSAGES } from '../i18n/game-messages';

const planetMessages = GAME_MESSAGES.world.planets;

export const PLANETS: Planet[] = [
  {
    id: 'solara',
    name: planetMessages.solara.name,
    description: planetMessages.solara.description,
    availableResourceIds: ['carbon', 'ferrite', 'oxygen'],
    resourceMultipliers: {
      carbon: 1,
      ferrite: 1,
      oxygen: 1,
      copper: 0,
      silica: 0,
      hydrogen: 0,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [],
    requiredShipTier: 0,
    orbitIndex: 0,
    orbitPosition: 0,
    unlockedByDefault: true,
    color: '#f59e0b',
    mineralColor: '#fcd34d',
    bgGradient: 'radial-gradient(circle at 50% 120%, #5b3411 0%, #1e160f 52%, #090b10 100%)',
  },
  {
    id: 'ferros',
    name: planetMessages.ferros.name,
    description: planetMessages.ferros.description,
    availableResourceIds: ['carbon', 'ferrite', 'oxygen'],
    resourceMultipliers: {
      carbon: 0.65,
      ferrite: 2.8,
      oxygen: 0.9,
      copper: 0,
      silica: 0,
      hydrogen: 0,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'oxygenCells', amount: 4 },
      { itemId: 'refinedMetal', amount: 3 },
    ],
    requiredShipTier: 1,
    orbitIndex: 1,
    orbitPosition: 1,
    unlockedByDefault: false,
    color: '#94a3b8',
    mineralColor: '#e2e8f0',
    bgGradient: 'radial-gradient(circle at 50% 120%, #334155 0%, #111827 55%, #05070d 100%)',
  },
  {
    id: 'verdara',
    name: planetMessages.verdara.name,
    description: planetMessages.verdara.description,
    availableResourceIds: ['carbon', 'ferrite', 'oxygen'],
    resourceMultipliers: {
      carbon: 0.85,
      ferrite: 0.7,
      oxygen: 3.2,
      copper: 0,
      silica: 0,
      hydrogen: 0,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'oxygenCells', amount: 6 },
      { itemId: 'mechanicalParts', amount: 2 },
    ],
    requiredShipTier: 1,
    orbitIndex: 2,
    orbitPosition: 3,
    unlockedByDefault: false,
    color: '#22c55e',
    mineralColor: '#86efac',
    bgGradient: 'radial-gradient(circle at 50% 120%, #14532d 0%, #052e16 50%, #030712 100%)',
  },
  {
    id: 'glassmere',
    name: planetMessages.glassmere.name,
    description: planetMessages.glassmere.description,
    availableResourceIds: ['carbon', 'oxygen', 'silica'],
    resourceMultipliers: {
      carbon: 0.7,
      ferrite: 0.45,
      oxygen: 1.25,
      copper: 0,
      silica: 3.45,
      hydrogen: 0.55,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'oxygenCells', amount: 8 },
      { itemId: 'mechanicalParts', amount: 4 },
      { itemId: 'basicCircuits', amount: 2 },
    ],
    requiredShipTier: 2,
    orbitIndex: 3,
    orbitPosition: 4,
    unlockedByDefault: false,
    color: '#e2e8f0',
    mineralColor: '#f8fafc',
    bgGradient: 'radial-gradient(circle at 50% 120%, #713f12 0%, #1f2937 55%, #020617 100%)',
  },
  {
    id: 'cinder',
    name: planetMessages.cinder.name,
    description: planetMessages.cinder.description,
    availableResourceIds: ['carbon', 'ferrite', 'oxygen'],
    resourceMultipliers: {
      carbon: 3.4,
      ferrite: 0.8,
      oxygen: 1.1,
      copper: 0,
      silica: 0,
      hydrogen: 0,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'mechanicalParts', amount: 3 },
      { itemId: 'basicCircuits', amount: 2 },
    ],
    requiredShipTier: 2,
    orbitIndex: 4,
    orbitPosition: 6,
    unlockedByDefault: false,
    color: '#f97316',
    mineralColor: '#fb923c',
    bgGradient: 'radial-gradient(circle at 50% 120%, #7c2d12 0%, #431407 50%, #09090b 100%)',
  },
  {
    id: 'voltaris',
    name: planetMessages.voltaris.name,
    description: planetMessages.voltaris.description,
    availableResourceIds: ['copper', 'oxygen'],
    resourceMultipliers: {
      carbon: 0,
      ferrite: 0.55,
      oxygen: 1.2,
      copper: 3.25,
      silica: 0.35,
      hydrogen: 0,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'oxygenCells', amount: 10 },
      { itemId: 'mechanicalParts', amount: 6 },
      { itemId: 'basicCircuits', amount: 5 },
    ],
    requiredShipTier: 3,
    orbitIndex: 5,
    orbitPosition: 7,
    unlockedByDefault: false,
    color: '#f97316',
    mineralColor: '#fdba74',
    bgGradient: 'radial-gradient(circle at 50% 120%, #451a03 0%, #172554 55%, #020617 100%)',
  },
  {
    id: 'nivalis',
    name: planetMessages.nivalis.name,
    description: planetMessages.nivalis.description,
    availableResourceIds: ['oxygen', 'silica', 'hydrogen'],
    resourceMultipliers: {
      carbon: 0,
      ferrite: 0.3,
      oxygen: 1.4,
      copper: 0,
      silica: 1.55,
      hydrogen: 3.35,
      titanium: 0,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'oxygenCells', amount: 12 },
      { itemId: 'basicCircuits', amount: 6 },
      { itemId: 'condensedCarbon', amount: 8 },
    ],
    requiredShipTier: 3,
    orbitIndex: 6,
    orbitPosition: 9,
    unlockedByDefault: false,
    color: '#38bdf8',
    mineralColor: '#bae6fd',
    bgGradient: 'radial-gradient(circle at 50% 120%, #0f172a 0%, #082f49 52%, #020617 100%)',
  },
  {
    id: 'titanreach',
    name: planetMessages.titanreach.name,
    description: planetMessages.titanreach.description,
    availableResourceIds: ['ferrite', 'titanium'],
    resourceMultipliers: {
      carbon: 0,
      ferrite: 1.45,
      oxygen: 0,
      copper: 0.35,
      silica: 0,
      hydrogen: 0,
      titanium: 3.1,
      rareCrystal: 0,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'copper', amount: 18 },
      { itemId: 'hydrogen', amount: 16 },
      { itemId: 'basicCircuits', amount: 10 },
      { itemId: 'mechanicalParts', amount: 8 },
    ],
    requiredShipTier: 4,
    orbitIndex: 7,
    orbitPosition: 11,
    unlockedByDefault: false,
    color: '#a78bfa',
    mineralColor: '#ddd6fe',
    bgGradient: 'radial-gradient(circle at 50% 120%, #312e81 0%, #111827 55%, #020617 100%)',
  },
  {
    id: 'umbra',
    name: planetMessages.umbra.name,
    description: planetMessages.umbra.description,
    availableResourceIds: ['carbon', 'rareCrystal'],
    resourceMultipliers: {
      carbon: 1.2,
      ferrite: 0,
      oxygen: 0,
      copper: 0,
      silica: 0.55,
      hydrogen: 0,
      titanium: 0.4,
      rareCrystal: 2.75,
      uranium: 0,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'copper', amount: 14 },
      { itemId: 'silica', amount: 20 },
      { itemId: 'hydrogen', amount: 14 },
      { itemId: 'basicCircuits', amount: 12 },
    ],
    requiredShipTier: 4,
    orbitIndex: 8,
    orbitPosition: 12,
    unlockedByDefault: false,
    color: '#ec4899',
    mineralColor: '#f9a8d4',
    bgGradient: 'radial-gradient(circle at 50% 120%, #4a044e 0%, #111827 58%, #020617 100%)',
  },
  {
    id: 'helion',
    name: planetMessages.helion.name,
    description: planetMessages.helion.description,
    availableResourceIds: ['hydrogen', 'uranium'],
    resourceMultipliers: {
      carbon: 0,
      ferrite: 0,
      oxygen: 0.25,
      copper: 0,
      silica: 0,
      hydrogen: 1.2,
      titanium: 0.55,
      rareCrystal: 0.8,
      uranium: 3.6,
      salvage: 0,
    },
    travelCost: [
      { itemId: 'titanium', amount: 18 },
      { itemId: 'rareCrystal', amount: 10 },
      { itemId: 'titaniumAlloy', amount: 4 },
      { itemId: 'basicCircuits', amount: 16 },
    ],
    requiredShipTier: 5,
    orbitIndex: 9,
    orbitPosition: 14,
    unlockedByDefault: false,
    color: '#a3e635',
    mineralColor: '#d9f99d',
    bgGradient: 'radial-gradient(circle at 50% 120%, #365314 0%, #0f172a 55%, #020617 100%)',
  },
];
