import { Recipe } from '../models';

export const RECIPES: Recipe[] = [
  {
    id: 'condensed-carbon',
    name: 'Condense Carbon',
    description: 'Compress raw carbon into a denser, more useful fuel block.',
    ingredients: [{ itemId: 'carbon', amount: 25 }],
    outputId: 'condensedCarbon',
    outputAmount: 1,
    tier: 1,
    unlockAtTotal: 20,
    icon: 'CC',
  },
  {
    id: 'refined-metal',
    name: 'Refine Metal',
    description: 'Purify ferrite into standardized structural metal.',
    ingredients: [{ itemId: 'ferrite', amount: 25 }],
    outputId: 'refinedMetal',
    outputAmount: 1,
    tier: 1,
    unlockAtTotal: 20,
    icon: 'RM',
  },
  {
    id: 'oxygen-cells',
    name: 'Pack Oxygen Cells',
    description: 'Stabilize oxygen into portable pressure and fuel cells.',
    ingredients: [{ itemId: 'oxygen', amount: 20 }],
    outputId: 'oxygenCells',
    outputAmount: 1,
    tier: 1,
    unlockAtTotal: 20,
    icon: 'OC',
  },
  {
    id: 'mechanical-parts',
    name: 'Assemble Mechanical Parts',
    description: 'Combine refined material into machine-grade moving components.',
    ingredients: [
      { itemId: 'refinedMetal', amount: 3 },
      { itemId: 'condensedCarbon', amount: 2 },
    ],
    outputId: 'mechanicalParts',
    outputAmount: 1,
    tier: 2,
    unlockAtTotal: 120,
    icon: 'MP',
  },
  {
    id: 'basic-circuits',
    name: 'Print Basic Circuits',
    description: 'Build simple control boards for miners and ship systems.',
    ingredients: [
      { itemId: 'oxygenCells', amount: 2 },
      { itemId: 'refinedMetal', amount: 2 },
    ],
    outputId: 'basicCircuits',
    outputAmount: 1,
    tier: 2,
    unlockAtTotal: 150,
    icon: 'BC',
  },
];
