import { Ship } from '../models';
import { GAME_MESSAGES } from '../i18n/game-messages';

const shipMessages = GAME_MESSAGES.progression.ships;

export const SHIPS: Ship[] = [
  {
    id: 'shuttle',
    name: shipMessages.shuttle.name,
    description: shipMessages.shuttle.description,
    buildCost: [
      { itemId: 'refinedMetal', amount: 10 },
      { itemId: 'mechanicalParts', amount: 2 },
    ],
    tier: 1,
    cargoCapacity: 20,
    travelSpeed: 1.6,
    icon: '🚀',
  },
  {
    id: 'hauler',
    name: shipMessages.hauler.name,
    description: shipMessages.hauler.description,
    buildCost: [
      { itemId: 'refinedMetal', amount: 14 },
      { itemId: 'oxygenCells', amount: 6 },
      { itemId: 'mechanicalParts', amount: 4 },
    ],
    tier: 1,
    cargoCapacity: 40,
    travelSpeed: 0.95,
    icon: '🚛',
  },
  {
    id: 'cruiser',
    name: shipMessages.cruiser.name,
    description: shipMessages.cruiser.description,
    buildCost: [
      { itemId: 'refinedMetal', amount: 18 },
      { itemId: 'mechanicalParts', amount: 8 },
      { itemId: 'basicCircuits', amount: 4 },
    ],
    tier: 2,
    cargoCapacity: 56,
    travelSpeed: 1.25,
    icon: '🛸',
  },
  {
    id: 'quantum_ship',
    name: shipMessages.quantum_ship.name,
    description: shipMessages.quantum_ship.description,
    buildCost: [
      { itemId: 'refinedMetal', amount: 30 },
      { itemId: 'mechanicalParts', amount: 12 },
      { itemId: 'basicCircuits', amount: 8 },
      { itemId: 'oxygenCells', amount: 10 },
    ],
    tier: 3,
    cargoCapacity: 96,
    travelSpeed: 1.9,
    icon: '✨',
  },
  {
    id: 'phase_clipper',
    name: shipMessages.phase_clipper.name,
    description: shipMessages.phase_clipper.description,
    buildCost: [
      { itemId: 'copper', amount: 18 },
      { itemId: 'silica', amount: 14 },
      { itemId: 'hydrogen', amount: 16 },
      { itemId: 'oxygenCells', amount: 12 },
      { itemId: 'basicCircuits', amount: 8 },
    ],
    tier: 4,
    cargoCapacity: 124,
    travelSpeed: 2.45,
    icon: '⚡',
  },
  {
    id: 'void_freighter',
    name: shipMessages.void_freighter.name,
    description: shipMessages.void_freighter.description,
    buildCost: [
      { itemId: 'copper', amount: 28 },
      { itemId: 'silica', amount: 20 },
      { itemId: 'hydrogen', amount: 18 },
      { itemId: 'mechanicalParts', amount: 12 },
      { itemId: 'basicCircuits', amount: 10 },
    ],
    tier: 4,
    cargoCapacity: 188,
    travelSpeed: 1.18,
    icon: '📦',
  },
  {
    id: 'singularity_ark',
    name: shipMessages.singularity_ark.name,
    description: shipMessages.singularity_ark.description,
    buildCost: [
      { itemId: 'titanium', amount: 28 },
      { itemId: 'rareCrystal', amount: 14 },
      { itemId: 'copper', amount: 22 },
      { itemId: 'basicCircuits', amount: 14 },
      { itemId: 'mechanicalParts', amount: 10 },
      { itemId: 'titaniumAlloy', amount: 4 },
    ],
    tier: 5,
    cargoCapacity: 248,
    travelSpeed: 1.82,
    icon: '🌌',
  },
];
