import { SpaceStationBlueprint } from '../models';

export const SPACE_STATION_BLUEPRINTS: SpaceStationBlueprint[] = [
  {
    id: 'orbital-outpost',
    tier: 0,
    name: 'Orbital Outpost',
    description: 'A compact dock ring that turns local mining output into organized launches.',
    buildCost: [
      { itemId: 'refinedMetal', amount: 8 },
      { itemId: 'basicCircuits', amount: 4 },
    ],
    cargoBonusMultiplier: 1.2,
    travelTimeMultiplier: 0.95,
  },
  {
    id: 'orbital-relay',
    tier: 1,
    name: 'Orbital Relay',
    description: 'A reinforced logistics platform with better scheduling and faster cargo cycling.',
    buildCost: [
      { itemId: 'refinedMetal', amount: 14 },
      { itemId: 'oxygenCells', amount: 8 },
      { itemId: 'basicCircuits', amount: 6 },
    ],
    cargoBonusMultiplier: 1.35,
    travelTimeMultiplier: 0.9,
  },
  {
    id: 'orbital-hub',
    tier: 2,
    name: 'Orbital Hub',
    description: 'A high-throughput command station built for distant worlds and heavy redistribution.',
    buildCost: [
      { itemId: 'refinedMetal', amount: 24 },
      { itemId: 'oxygenCells', amount: 12 },
      { itemId: 'mechanicalParts', amount: 8 },
      { itemId: 'basicCircuits', amount: 10 },
    ],
    cargoBonusMultiplier: 1.5,
    travelTimeMultiplier: 0.86,
  },
  {
    id: 'orbital-anchor',
    tier: 3,
    name: 'Orbital Anchor',
    description: 'A deep-route anchor with expanded tanks, relay towers, and hardened transfer spines.',
    buildCost: [
      { itemId: 'copper', amount: 18 },
      { itemId: 'silica', amount: 18 },
      { itemId: 'hydrogen', amount: 16 },
      { itemId: 'basicCircuits', amount: 12 },
      { itemId: 'mechanicalParts', amount: 8 },
    ],
    cargoBonusMultiplier: 1.72,
    travelTimeMultiplier: 0.82,
  },
  {
    id: 'orbital-foundry',
    tier: 4,
    name: 'Orbital Foundry',
    description: 'An industrial ring built to process heavy cargo and coordinate long-haul fleet windows.',
    buildCost: [
      { itemId: 'titanium', amount: 18 },
      { itemId: 'rareCrystal', amount: 8 },
      { itemId: 'titaniumAlloy', amount: 3 },
      { itemId: 'basicCircuits', amount: 16 },
      { itemId: 'mechanicalParts', amount: 12 },
    ],
    cargoBonusMultiplier: 1.95,
    travelTimeMultiplier: 0.78,
  },
  {
    id: 'orbital-citadel',
    tier: 5,
    name: 'Orbital Citadel',
    description: 'A reactor-fed apex station meant for uranium lanes, strategic stockpiles, and system-wide control.',
    buildCost: [
      { itemId: 'uranium', amount: 24 },
      { itemId: 'rareCrystal', amount: 12 },
      { itemId: 'reactorCores', amount: 3 },
      { itemId: 'titaniumAlloy', amount: 6 },
      { itemId: 'basicCircuits', amount: 20 },
    ],
    cargoBonusMultiplier: 2.25,
    travelTimeMultiplier: 0.72,
  },
];
