import { Tool } from '../models';

export const INITIAL_TOOLS: Tool[] = [
  {
    id: 'hands',
    name: 'Bare Hands',
    description: 'You dig with your bare hands. It works... barely.',
    baseCost: 0,
    resourcesPerClick: 1,
    level: 1,
    maxLevel: 1,
    costScaling: 1,
    icon: '✊',
  },
  {
    id: 'pickaxe',
    name: 'Makeshift Pickaxe',
    description: 'Crafted from alien rock. +2 per click.',
    baseCost: 25,
    resourcesPerClick: 3,
    level: 0,
    maxLevel: 5,
    costScaling: 1.8,
    icon: '⛏️',
  },
  {
    id: 'laser',
    name: 'Laser Cutter',
    description: 'Salvaged tech. Slices through rock. +8 per click.',
    baseCost: 200,
    resourcesPerClick: 10,
    level: 0,
    maxLevel: 5,
    costScaling: 2.0,
    icon: '🔫',
  },
  {
    id: 'plasma',
    name: 'Plasma Drill',
    description: 'Military-grade extraction. +30 per click.',
    baseCost: 2000,
    resourcesPerClick: 40,
    level: 0,
    maxLevel: 5,
    costScaling: 2.2,
    icon: '🔥',
  },
  {
    id: 'quantum',
    name: 'Quantum Extractor',
    description: 'Bends spacetime to pull minerals. +150 per click.',
    baseCost: 25000,
    resourcesPerClick: 200,
    level: 0,
    maxLevel: 5,
    costScaling: 2.5,
    icon: '⚛️',
  },
];
