import { ExpeditionState, GeneratedPlanetSeed } from './expedition.model';
import { ItemId, ResourceId } from './resource.model';
import { OwnedShip, ShipRoute } from './ship.model';
import { OwnedSpaceStation } from './space-station.model';
import { ActiveInvasionRaid, ActiveInvasionStrike, FactionAngerEvent, InvasionFleet, PlanetThreatState, RaidEvent } from './combat.model';
import { DeployedGarrison, MilitaryUnitTransit } from './military.model';
import { ActiveAttack, AttackResult } from './enemy-system.model';
import { TutorialState } from './tutorial.model';

export interface GameState {
  version: number;
  planetInventories: Record<string, Record<ItemId, number>>;
  stationInventories: Record<string, Record<ItemId, number>>;
  generatedPlanets: GeneratedPlanetSeed[];
  expedition: ExpeditionState;
  activeResourceId: ResourceId;
  globallyUnlockedRecipeIds: string[];
  tutorial: TutorialState;
  upgradeLevels: Record<string, number>;
  autoMinerCounts: Record<string, number>;
  builtShipPartIds: string[];
  discoveredPlanetIds: string[];
  totalClicks: number;
  totalMined: Record<ResourceId, number>;
  currentPlanetId: string;
  shipLaunched: boolean;
  ships: OwnedShip[];
  shipRoutes: ShipRoute[];
  spaceStations: OwnedSpaceStation[];
  nextShipId: number;
  nextShipRouteId: number;
  lastTickAt: number;
  planetThreats: Record<string, PlanetThreatState>;
  combatLog: (RaidEvent | AttackResult | FactionAngerEvent)[];
  combatUnlocked: boolean;
  deployedGarrisons: DeployedGarrison[];
  militaryUnlocked: boolean;
  unitsInTransit: MilitaryUnitTransit[];
  activeAttacks: ActiveAttack[];
  discoveredEnemySystemIds: string[];
  offensiveUnlocked: boolean;
  invasionFleets: InvasionFleet[];
  activeInvasionStrikes: ActiveInvasionStrike[];
  activeInvasionRaids: ActiveInvasionRaid[];
  nextInvasionAt: number;
  attackCooldowns: Record<string, number>;
  militaryBuildingLevels: Record<string, number>;
  factionAnger: number;
  lastPlayerAttackAt: number;
  lastPlayerAttackOriginPlanetId: string | null;
  pendingAttackResults: AttackResult[];
}
